//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEmployeesSystemEntities1 : DbContext
    {
        public dbEmployeesSystemEntities1()
            : base("name=dbEmployeesSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBusinessUnit> tblBusinessUnits { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
    
        public virtual int GetEmployeeDetails(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetEmployeeDetails", employeeIdParameter);
        }
    
        public virtual ObjectResult<proc_GetEmployeeDetails_Result> proc_GetEmployeeDetails(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetEmployeeDetails_Result>("proc_GetEmployeeDetails", employeeIdParameter);
        }
    
        public virtual ObjectResult<string> proc_EmployeeLogin(Nullable<int> employee_id, string password)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_EmployeeLogin", employee_idParameter, passwordParameter);
        }
    
        public virtual ObjectResult<storedproc_GetEmployeeDetails_Result> storedproc_GetEmployeeDetails(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<storedproc_GetEmployeeDetails_Result>("storedproc_GetEmployeeDetails", employeeIdParameter);
        }
    
        public virtual ObjectResult<proc_GetAllEmployees_Result> proc_GetAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllEmployees_Result>("proc_GetAllEmployees");
        }
    
        public virtual ObjectResult<storedproc_GetAllEmployees_Result> storedproc_GetAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<storedproc_GetAllEmployees_Result>("storedproc_GetAllEmployees");
        }
    
        public virtual ObjectResult<procedure_GetAllEmployees_Result> procedure_GetAllEmployees(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procedure_GetAllEmployees_Result>("procedure_GetAllEmployees", employee_idParameter);
        }
    
        public virtual ObjectResult<proc_GetAllEmployees1_Result> proc_GetAllEmployees1(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllEmployees1_Result>("proc_GetAllEmployees1", employee_idParameter);
        }
    
        public virtual ObjectResult<GetAllEmployees_Result> GetAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEmployees_Result>("GetAllEmployees");
        }
    
        public virtual ObjectResult<proc_GetEmployeesForAdmin_Result> proc_GetEmployeesForAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetEmployeesForAdmin_Result>("proc_GetEmployeesForAdmin");
        }
    
        public virtual ObjectResult<GetDepartmentAndUnitNames_Result> GetDepartmentAndUnitNames(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentAndUnitNames_Result>("GetDepartmentAndUnitNames", employee_idParameter);
        }
    
        public virtual ObjectResult<string> proc_CheckAlreadyExistingEmployee(string mobile_Number)
        {
            var mobile_NumberParameter = mobile_Number != null ?
                new ObjectParameter("Mobile_Number", mobile_Number) :
                new ObjectParameter("Mobile_Number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_CheckAlreadyExistingEmployee", mobile_NumberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_GenerateEmployee_id(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_GenerateEmployee_id", employee_idParameter);
        }
    }
}
